[package]
authors.workspace = true
categories.workspace = true
description = "A tracing layer for aliyun sls"
edition.workspace = true
homepage = "https://github.com/lightsing/tracing-aliyun-sls/tree/master/crates/tracing-aliyun-sls"
keywords = ["tracing", "aliyun", "sls"]
license.workspace = true
name = "tracing-aliyun-sls"
repository.workspace = true
rust-version.workspace = true
version = "0.3.0"

[package.metadata.docs.rs]
no-default-features = true
features = [
  "reqwest-rustls",
  "lz4",
  "persist",
  "aliyun-sls/inline-keypairs-8",
  "aliyun-sls/inline-tags-8",
]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
aliyun-sls = { path = "../aliyun-sls", default-features = false, features = ["reporter"] }
bitflags.workspace = true
compact_str.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["std"] }

[features]
default = ["reqwest-default-tls"]

# re-export aliyun-sls features
deflate = ["aliyun-sls/deflate"]
lz4 = ["aliyun-sls/lz4"]
persist = ["aliyun-sls/persist"]

reqwest = ["aliyun-sls/reqwest"]
reqwest-default-tls = ["aliyun-sls/reqwest-default-tls"]
reqwest-rustls = ["aliyun-sls/reqwest-rustls"]

nyquest = ["aliyun-sls/nyquest"]
